In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt 
%matplotlib inline
from scipy.stats  import gaussian_kde
import plotly.graph_objects as go

In [2]:
df = pd.read_csv("data/train.csv")

In [3]:
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,2141-RRYGO,Female,0,No,No,4,Yes,No,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),68.65,261.25,Yes
1,8984-EYLLL,Male,0,Yes,No,64,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,Two year,Yes,Electronic check,105.25,6823.40,No
2,3778-FOAQW,Female,0,Yes,No,24,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.15,456.85,No
3,6663-JOCQO,Male,0,Yes,Yes,31,Yes,Yes,DSL,Yes,...,No,Yes,No,Yes,One year,Yes,Bank transfer (automatic),75.25,2344.50,No
4,3932-IJWDZ,Male,0,No,No,45,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.65,4747.85,No

In [4]:
df.shape

(5634, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        5634 non-null   object
 1   gender            5634 non-null   object
 2   seniorcitizen     5634 non-null   int64
 3   partner           5634 non-null   object
 4   dependents        5634 non-null   object
 5   tenure            5634 non-null   int64
 6   phoneservice      5634 non-null   object
 7   multiplelines     5634 non-null   object
 8   internetservice   5634 non-null   object
 9   onlinesecurity    5634 non-null   object
 10  onlinebackup      5634 non-null   object
 11  deviceprotection  5634 non-null   object
 12  techsupport       5634 non-null   object
 13  streamingtv       5634 non-null   object
 14  streamingmovies   5634 non-null   object
 15  contract          5634 non-null   object
 16  paperlessbilling  5634 non-null   object
 17  paymentmethod     5634 non-null   object
 18  monthlycharges    5634 non-null   float64
 19  totalcharges      5626 non-null   float64
 20  churn             5634 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 924.5+ KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
seniorcitizen,5634.0,0.163294,0.369667,0.00,0.0000,0.000,0.0000,1.00
tenure,5634.0,32.632410,24.664055,0.00,9.0000,29.000,56.0000,72.00
monthlycharges,5634.0,64.864013,30.086419,18.25,35.7125,70.425,89.8500,118.65
totalcharges,5626.0,2301.902746,2275.289050,18.80,399.7000,1410.250,3871.4625,8564.75

In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5629    False
5630    False
5631    False
5632    False
5633    False
Length: 5634, dtype: bool

In [8]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        8
churn               0
dtype: int64

In [9]:
df.isna().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        8
churn               0
dtype: int64

In [10]:
columns = ['tenure','monthlycharges','totalcharges']

for col in columns:
    print(df[col].skew())

0.21797246383954386
-0.2285118727498862
0.9324748550631611

In [11]:
columns = ['tenure','monthlycharges','totalcharges']

for col in columns:
    fig = px.histogram(
        data_frame=df,
        x=col,
        nbins=30,
        title=f"Distribution of {col}"
    )

    fig.update_layout(
        xaxis_title=col,
        yaxis_title="Frequency"
    )

    fig.show()

In [12]:
columns = ['tenure','monthlycharges','totalcharges']

for col in columns:

    data = df[col].dropna()
    kde = gaussian_kde(data)

    x_values = np.linspace(
        data.min(),
        data.max(),
        500
    )

    y_values = kde(x_values)

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=x_values,
            y=y_values,
            mode="lines",
            name="KDE"
        )
    )

    fig.update_layout(
        title= f"KDE Distribution of {col}",
        xaxis_title=col,
        yaxis_title="Density"
    )

    fig.show()

In [13]:
columns = ['tenure','monthlycharges','totalcharges']

fig = go.Figure()


for col in columns:

    fig.add_trace(
        go.Box(
            y=df[col],
            name=col
        )
    )

    fig.update_layout(
        title="Boxplot comparision of Numerical Features",
        yaxis_title="value"
    )

    fig.show()

In [35]:
outlier_summary = []
columns = ['tenure','monthlycharges','totalcharges']

for col in columns:
     q1 = df[col].quantile(0.25)
     q3 = df[col].quantile(0.75)

     iqr = q3-q1

     lower_bound = q1 - 1.5 * iqr
     upper_bound = q3 + 1.5 * iqr

     outliers = df[
          (df[col] < lower_bound) | (df[col] > upper_bound)
     ]

     outlier_summary = [{
          "feature":col,
          "q1":q1,
          "q3":q3,
          "iqr":iqr,
          "lower_bound":lower_bound,
          "upper_bound":upper_bound,
          "outlier_count":len(outliers),
          "outlier%": len(outliers) / len(df) * 100
     }]

     outlier_df = pd.DataFrame(outlier_summary)
     print(outlier_df)

  feature   q1    q3   iqr  lower_bound  upper_bound  outlier_count  outlier%
0  tenure  9.0  56.0  47.0        -61.5        126.5              0       0.0
          feature       q1     q3      iqr  lower_bound  upper_bound  \
0  monthlycharges  35.7125  89.85  54.1375    -45.49375    171.05625

   outlier_count  outlier%
0              0       0.0
        feature     q1         q3        iqr  lower_bound  upper_bound  \
0  totalcharges  399.7  3871.4625  3471.7625  -4807.94375   9079.10625

   outlier_count  outlier%
0              0       0.0

In [15]:
df.head(2)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,2141-RRYGO,Female,0,No,No,4,Yes,No,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),68.65,261.25,Yes
1,8984-EYLLL,Male,0,Yes,No,64,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,Two year,Yes,Electronic check,105.25,6823.40,No

In [16]:
df['churn'].value_counts()

churn
No     4139
Yes    1495
Name: count, dtype: int64

In [17]:
df['churn'].isnull().sum()

np.int64(0)

In [18]:
cat_columns = df.select_dtypes(
    include=['object','category']

).columns.tolist()

print(cat_columns)

['customerid', 'gender', 'partner', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod', 'churn']

In [19]:
cat_features = [
    col for col in cat_columns
    if col != 'churn'
]

print(cat_features)

['customerid', 'gender', 'partner', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod']

In [20]:
for col in cat_features:
    print(f"{col}: {df[col].nunique()} unique values")

customerid: 5634 unique values
gender: 2 unique values
partner: 2 unique values
dependents: 2 unique values
phoneservice: 2 unique values
multiplelines: 3 unique values
internetservice: 3 unique values
onlinesecurity: 3 unique values
onlinebackup: 3 unique values
deviceprotection: 3 unique values
techsupport: 3 unique values
streamingtv: 3 unique values
streamingmovies: 3 unique values
contract: 3 unique values
paperlessbilling: 2 unique values
paymentmethod: 4 unique values

In [21]:
for col in cat_features:
    print(df[col].value_counts())

customerid
1098-KFQEC    1
2141-RRYGO    1
0562-FGDCR    1
8565-WUXZU    1
2869-ADAWR    1
             ..
0774-RMNUW    1
1170-SASML    1
3932-IJWDZ    1
6663-JOCQO    1
3778-FOAQW    1
Name: count, Length: 5634, dtype: int64
gender
Male      2839
Female    2795
Name: count, dtype: int64
partner
No     2903
Yes    2731
Name: count, dtype: int64
dependents
No     3965
Yes    1669
Name: count, dtype: int64
phoneservice
Yes    5098
No      536
Name: count, dtype: int64
multiplelines
No                  2719
Yes                 2379
No phone service     536
Name: count, dtype: int64
internetservice
Fiber optic    2490
DSL            1924
No             1220
Name: count, dtype: int64
onlinesecurity
No                     2786
Yes                    1628
No internet service    1220
Name: count, dtype: int64
onlinebackup
No                     2471
Yes                    1943
No internet service    1220
Name: count, dtype: int64
deviceprotection
No                     2465
Yes                    1949
No internet service    1220
Name: count, dtype: int64
techsupport
No                     2791
Yes                    1623
No internet service    1220
Name: count, dtype: int64
streamingtv
No                     2256
Yes                    2158
No internet service    1220
Name: count, dtype: int64
streamingmovies
No                     2225
Yes                    2189
No internet service    1220
Name: count, dtype: int64
contract
Month-to-month    3092
Two year          1359
One year          1183
Name: count, dtype: int64
paperlessbilling
Yes    3353
No     2281
Name: count, dtype: int64
paymentmethod
Electronic check             1875
Mailed check                 1290
Bank transfer (automatic)    1237
Credit card (automatic)      1232
Name: count, dtype: int64

In [22]:
for col in cat_features:
    percentages = (
        df[col]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )

    print(percentages)

customerid
1098-KFQEC    0.02
2141-RRYGO    0.02
0562-FGDCR    0.02
8565-WUXZU    0.02
2869-ADAWR    0.02
              ...
0774-RMNUW    0.02
1170-SASML    0.02
3932-IJWDZ    0.02
6663-JOCQO    0.02
3778-FOAQW    0.02
Name: proportion, Length: 5634, dtype: float64
gender
Male      50.39
Female    49.61
Name: proportion, dtype: float64
partner
No     51.53
Yes    48.47
Name: proportion, dtype: float64
dependents
No     70.38
Yes    29.62
Name: proportion, dtype: float64
phoneservice
Yes    90.49
No      9.51
Name: proportion, dtype: float64
multiplelines
No                  48.26
Yes                 42.23
No phone service     9.51
Name: proportion, dtype: float64
internetservice
Fiber optic    44.20
DSL            34.15
No             21.65
Name: proportion, dtype: float64
onlinesecurity
No                     49.45
Yes                    28.90
No internet service    21.65
Name: proportion, dtype: float64
onlinebackup
No                     43.86
Yes                    34.49
No internet service    21.65
Name: proportion, dtype: float64
deviceprotection
No                     43.75
Yes                    34.59
No internet service    21.65
Name: proportion, dtype: float64
techsupport
No                     49.54
Yes                    28.81
No internet service    21.65
Name: proportion, dtype: float64
streamingtv
No                     40.04
Yes                    38.30
No internet service    21.65
Name: proportion, dtype: float64
streamingmovies
No                     39.49
Yes                    38.85
No internet service    21.65
Name: proportion, dtype: float64
contract
Month-to-month    54.88
Two year          24.12
One year          21.00
Name: proportion, dtype: float64
paperlessbilling
Yes    59.51
No     40.49
Name: proportion, dtype: float64
paymentmethod
Electronic check             33.28
Mailed check                 22.90
Bank transfer (automatic)    21.96
Credit card (automatic)      21.87
Name: proportion, dtype: float64

In [23]:
for col in cat_features:
    counts = (
        df[col]
        .value_counts()
        .reset_index()
    )
    counts.columns = [col,'count']

    fig = px.bar(
        counts,
        x=col,
        y='count',
        text = 'count',
        title=f"distribution of {col}"
    )

    fig.update_layout(
        xaxis_title=col,
        yaxis_title = "number of customers"
    )

    fig.show()

In [24]:
# detect rare categories
for col in cat_features:
    percentages = (
        df[col]
        .value_counts(normalize=True)
        .mul(100)
    )

    print(percentages[percentages<1])

customerid
1098-KFQEC    0.017749
2141-RRYGO    0.017749
0562-FGDCR    0.017749
8565-WUXZU    0.017749
2869-ADAWR    0.017749
                ...
0774-RMNUW    0.017749
1170-SASML    0.017749
3932-IJWDZ    0.017749
6663-JOCQO    0.017749
3778-FOAQW    0.017749
Name: proportion, Length: 5634, dtype: float64
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)
Series([], Name: proportion, dtype: float64)

In [25]:
cat_miss = df[cat_features].isnull().sum()
cat_miss = cat_miss[
    cat_miss > 0
]

print(cat_miss)

Series([], dtype: int64)

In [26]:
for col in cat_features:
    print(
        df[col]
        .astype(str)
        .str.strip()
        .value_counts()
    )

customerid
1098-KFQEC    1
2141-RRYGO    1
0562-FGDCR    1
8565-WUXZU    1
2869-ADAWR    1
             ..
0774-RMNUW    1
1170-SASML    1
3932-IJWDZ    1
6663-JOCQO    1
3778-FOAQW    1
Name: count, Length: 5634, dtype: int64
gender
Male      2839
Female    2795
Name: count, dtype: int64
partner
No     2903
Yes    2731
Name: count, dtype: int64
dependents
No     3965
Yes    1669
Name: count, dtype: int64
phoneservice
Yes    5098
No      536
Name: count, dtype: int64
multiplelines
No                  2719
Yes                 2379
No phone service     536
Name: count, dtype: int64
internetservice
Fiber optic    2490
DSL            1924
No             1220
Name: count, dtype: int64
onlinesecurity
No                     2786
Yes                    1628
No internet service    1220
Name: count, dtype: int64
onlinebackup
No                     2471
Yes                    1943
No internet service    1220
Name: count, dtype: int64
deviceprotection
No                     2465
Yes                    1949
No internet service    1220
Name: count, dtype: int64
techsupport
No                     2791
Yes                    1623
No internet service    1220
Name: count, dtype: int64
streamingtv
No                     2256
Yes                    2158
No internet service    1220
Name: count, dtype: int64
streamingmovies
No                     2225
Yes                    2189
No internet service    1220
Name: count, dtype: int64
contract
Month-to-month    3092
Two year          1359
One year          1183
Name: count, dtype: int64
paperlessbilling
Yes    3353
No     2281
Name: count, dtype: int64
paymentmethod
Electronic check             1875
Mailed check                 1290
Bank transfer (automatic)    1237
Credit card (automatic)      1232
Name: count, dtype: int64

In [27]:
contract_churn = pd.crosstab(
    df['contract'],
    df['churn'],
    normalize='index'
) *100

contract_churn = contract_churn.reset_index()
contract_churn

churn        contract         No        Yes
0      Month-to-month  57.050453  42.949547
1            One year  89.433643  10.566357
2            Two year  96.909492   3.090508

In [28]:
fig = px.bar(
    contract_churn,
    x='contract',
    y=['No','Yes'],
    title='churn distribution by contract',
    barmode='stack'
)

fig.update_layout(
    xaxis_title='contract type',
    yaxis_title='percentage (%)'
)

fig.show()

In [29]:
def cat_churn_analysis(df,column):
    churn_rate=(
        df.groupby(column)['churn']
        .apply(lambda x: (x == 'Yes').mean() * 100)
        .reset_index(name='churn_rate')
    )

    fig = px.bar(
        churn_rate,
        x=column,
        y='churn_rate',
        text=churn_rate['churn_rate'].round(2),
        title=f"churn rate by {column}"
    )

    fig.update_layout(
        xaxis_title=column,
        yaxis_title='churn_rate (%)'
    )

    fig.show()

    return churn_rate

In [30]:
for col in cat_features:
    result = cat_churn_analysis(df,col)
    print(result)

      customerid  churn_rate
0     0002-ORFBO         0.0
1     0003-MKNFE         0.0
2     0004-TLHLJ       100.0
3     0011-IGKFF       100.0
4     0013-EXCHZ       100.0
...          ...         ...
5629  9987-LUTYD         0.0
5630  9992-RRAMN       100.0
5631  9992-UJOEL         0.0
5632  9993-LHIEB         0.0
5633  9995-HOTOH         0.0

[5634 rows x 2 columns]

   gender  churn_rate
0  Female   26.976744
1    Male   26.100740

  partner  churn_rate
0      No   33.585946
1     Yes   19.040644

  dependents  churn_rate
0         No   31.349306
1        Yes   15.098862

  phoneservice  churn_rate
0           No   25.932836
1          Yes   26.598666

      multiplelines  churn_rate
0                No   25.009195
1  No phone service   25.932836
2               Yes   28.415301

  internetservice  churn_rate
0             DSL   18.814969
1     Fiber optic   42.008032
2              No    7.131148

        onlinesecurity  churn_rate
0                   No   42.139268
1  No internet service    7.131148
2                  Yes   14.373464

          onlinebackup  churn_rate
0                   No   40.105221
1  No internet service    7.131148
2                  Yes   21.461657

      deviceprotection  churn_rate
0                   No   39.066937
1  No internet service    7.131148
2                  Yes   22.832222

           techsupport  churn_rate
0                   No   41.597994
1  No internet service    7.131148
2                  Yes   15.218731

           streamingtv  churn_rate
0                   No   34.131206
1  No internet service    7.131148
2                  Yes   29.564411

       streamingmovies  churn_rate
0                   No   34.426966
1  No internet service    7.131148
2                  Yes   29.328460

         contract  churn_rate
0  Month-to-month   42.949547
1        One year   10.566357
2        Two year    3.090508

  paperlessbilling  churn_rate
0               No   16.220956
1              Yes   33.552043

               paymentmethod  churn_rate
0  Bank transfer (automatic)   16.976556
1    Credit card (automatic)   15.746753
2           Electronic check   45.386667
3               Mailed check   18.604651

In [31]:
num_features = ['tenure','monthlycharges','totalcharges']

In [32]:
corr_matrix = df[num_features].corr()
print (corr_matrix)

fig = px.imshow(
    corr_matrix,
    text_auto=True,
    title='correlation matrix of numerical features',
    aspect='auto'
)

fig.update_layout(
    xaxis_title='features',
    yaxis_title='features'
)

fig.show()

                  tenure  monthlycharges  totalcharges
tenure          1.000000        0.246367      0.826454
monthlycharges  0.246367        1.000000      0.650434
totalcharges    0.826454        0.650434      1.000000

In [33]:
miss = df.isnull().sum()
miss = miss[miss > 0]
print(miss)

totalcharges    8
dtype: int64

In [34]:
miss_percent = (
    df.isnull().mean() * 100
)
miss_percent = miss_percent[
    miss_percent > 0
]

print(miss_percent)

totalcharges    0.141995
dtype: float64